### ISSUE TITLE
Support for downloading artifacts

### ISSUE THREAD

**Issue by henriquegemignani** [gaqzi/py-gocd#3]
Related API calls:
http://api.go.cd/current/#get-artifact-file

The API call itself is rather simple, however I don't know the best place in py-gocd to add this feature.

**Comment by gaqzi** [comment]
I would create a new `Artifact` class in a module `gocd.api.artifact` and then work it from there. Sadly there's a lot of information needed to get artifacts so the bulk of the work will require a bunch of information to get anything.

I probably would make it work something like:

```python
from gocd.api import Artifact

# stage_counter should have a default value of 1,
# since at least in my experience it's 90% of the time 
# only going to be 1 run through :)
artifact = Artifact('A-Pipeline', counter=123, stage='generate', 
                    [stage_counter=1], job='generate')
artifact.list()
artifact.get('secret-file.pgp')
artifact.get_directory('output/')
```

So in the long run I think implementing a `PipelineInstance` class that you can instantiate from a [history] call would be good, that could then be used as an easy wrapper to get/list all the artifacts. :)

[history]: https://github.com/gaqzi/py-gocd/blob/master/gocd/api/pipeline.py#L21

**Comment by henriquegemignani** [comment]
That seems like a good API. The get/get_directory methods would return and urllib connection so the use user is responsible for writing the file to disk (or memory), right?

For my use case, I wouldn't use the helper ```PipelineInstance``` is not necessary, since I plan to use this from inside a GoCD job to fetch from a material.

I'll hack up a pull request for this. How do I run the tests for this project? I looked earlier and couldn't figure it out.

**Comment by gaqzi** [comment]
Yeah that sounds good, I didn't actually consider at all how the file would actually get saved afterwards. :)
I'm all for having some easy helpers for saving it directly into a file/string though if you feel like it.

For testing/getting it setup from scratch this is what I would do, I assume you know about [virtualenvs]:

```shell
$ mkvirtualenv py-gocd
$ make develop  # installs dependencies, sets up a pre-push hooks with some sane defaults
$ py.test  # runs the test suite
```

There's also a `$ make test` command, but it relies on tox and there being multiple versions of Python available so unless you have the specified versions on your computer it may not work.

The API portions of the test suite I've been using [vcr] to record connections. So we don't have to have a properly configured Go server around for every unit test run. This does rely on there being a go server to connect to and get the proper result from the first time around, but it's fairly straightforward. 

If you have any more questions please don't hesitate to ask! :)

[virtualenvs]: https://pypi.python.org/pypi/virtualenvwrapper
[vcr]: https://pypi.python.org/pypi/vcrpy/
